[package]
name = "guiedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "guiedit"

[dependencies]
sfml = "0.18.1"

[dev-dependencies]
rand = "0.8.5"
sfml = "0.18.1"
