[package]
name = "guiedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "guiedit"

[dependencies]
egui = "0.19.0"
egui-sfml = { git = "https://github.com/aleokdev/egui-sfml", branch = "time-fix" }
sfml = "0.18.1"

[dev-dependencies]
rand = "0.8.5"
sfml = "0.18.1"
guiedit_derive = { path = "derive" }

[workspace]
members = ["derive"]
